package com.deeplinkly.reactnative

import com.facebook.react.bridge.ReactApplicationContext

/**
 * New-architecture superclass.
 *
 * `NativeDeeplinklySpec` is generated by codegen from `src/NativeDeeplinkly.ts`,
 * so the method surface below is enforced by the TypeScript spec rather than
 * restated here. The `src/oldarch` twin declares the same surface by hand
 * against `ReactContextBaseJavaModule`; `DeeplinklyModule` implements it once
 * and neither architecture can drift from the other.
 */
abstract class DeeplinklyModuleSpec(context: ReactApplicationContext) :
  NativeDeeplinklySpec(context)
